services:
  web:
    build: .
    entrypoint: /app/entrypoint.sh      # Burada entrypoint belirt
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PORT=8000
    restart: always
