services:
  web:
    build: .
    entrypoint: /app/entrypoint.sh      # Burada entrypoint belirt
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PORT=8080
    restart: always
