# Generated by Django 5.1.6 on 2025-03-04 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_name',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
