# Generated by Django 5.1.6 on 2025-06-01 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_comment_last_name_alter_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Verification Token')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscription Date')),
                ('subscription_source', models.CharField(choices=[('comment_form', 'Comment Form'), ('website_form', 'Website Form')], default='comment_form', max_length=50, verbose_name='Subscription Source')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='first_name',
        ),
    ]
