# Generated by Django 5.1.6 on 2025-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_first_name_comment_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
    ]
