# Generated by Django 5.1.6 on 2025-06-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newslettersubscription_delete_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='subscription_source',
            field=models.CharField(choices=[('comment_form', 'Comment Form'), ('website_form', 'Website Form'), ('api', 'API')], default='website_form', max_length=50, verbose_name='Subscription Source'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['email'], name='core_newsle_email_144892_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['is_verified'], name='core_newsle_is_veri_246d02_idx'),
        ),
    ]
