# Generated by Django 5.2.2 on 2025-09-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepagecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageContent',
        ),
    ]
