# Generated by Django 5.1.6 on 2025-05-20 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comment_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('short_description', models.CharField(blank=True, max_length=250, verbose_name='Kısa Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Kapak Görseli')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Proje Linki (örn. GitHub, canlı demo)')),
                ('technologies', models.CharField(blank=True, max_length=250, verbose_name='Teknolojiler (virgülle)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Vitrinde Göster')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='core.tag')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-date_posted'],
            },
        ),
    ]
